packages:
  - apps/**/**
  - packages/**/**

catalog:
  # Dependencies
  react: ^19.0.0
  react-dom: ^19.0.0
  framer-motion: '11.17.0'

  # Dev Dependencies
  typescript: ~5.7.2
  '@types/react': ^19.0.2
  '@types/react-dom': ^19.0.2
  '@types/node': ^22.10.2
  '@react-types/shared': '3.26.0'

  # Build Dependencies
  vite: ^6.0.5
  vite-plugin-dts: ^4.4.0
