packages:
  - apps/**/**
  - packages/**/**

catalog:
  # Dependencies
  next: 15.4.7
  react: ^19.0.0
  react-dom: ^19.0.0
  framer-motion: 11.17.0

  # Dev Dependencies
  typescript: ~5.7.2
  '@types/node': ^22.10.2
  '@types/react': ^19.0.2
  '@types/react-dom': ^19.0.2
  eslint-config-next: 15.4.7
  '@react-types/shared': 3.26.0

  # Build Dependencies
  vite: ^7.1.12
  vite-plugin-dts: ^4.5.4
