name: Release

on:
  push:
    paths:
      - ".changeset/**"
      - "packages/**"
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          version: "9.6.0"
          node-version-file: ".nvmrc"
          registry-url: "https://registry.npmjs.org"
          cache: "pnpm"

      - name: Setup Git User
        shell: bash
        run: |
          git config --global user.email "muneebmughal3324@gmail.com"
          git config --global user.name "Muneeb Mughal"

      - name: Install dependencies
        shell: bash
        run: pnpm install

      - name: Tests
        run: pnpm run test

      - name: Build
        id: build
        continue-on-error: false
        run: pnpm run build

      - name: Create Release Pull Request or Publish to npm
        if: steps.build.outcome == 'success'
        id: changesets
        uses: changesets/action@v1
        with:
          version: pnpm changeset:version
          title: "ci(changesets): :package: version packages"
          commit: "ci(changesets): version packages"
          publish: pnpm changeset:release
          setupGitUser: true
        env:
          CI: true
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
